blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog_app import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('all_blogs/', views.all_blogs, name='all_blogs'),
    path('about/', views.about, name='about'),
    #path('contact', views.contact, name='contact'),
    path('admin/', admin.site.urls),
    path('blog_app/', include('blog_app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/blog_app/urls.py
from django.urls import path
from . import views

app_name = 'blog'

#added second urls so that the app can handle url requests without calling to the main project urls.
urlpatterns = [
    path('', views.home, name='home'),
    path('all_blogs/', views.all_blogs, name='all_blogs'),
    path('about/', views.about, name='about'),
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

blog/blog_app/models.py
from django.db import models

# Create your models here.
#setting what data fields the admin page will ask for when adding a blog post
class Blog(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    date = models.DateField()
    image = models.ImageField(upload_to='blog_app/images/')
    
    def __str__(self):
        return self.title

blog/blog_app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Blog
# Create your views here.
#defining what's being rendered based on requests by the browser
def home(request):
    return render(request, 'blog_app/home.html')
def about(request):
    return render(request, 'blog_app/about.html')

#Setting up the all_blogs page to automatically get and sort the blogs on one page from a database
def all_blogs(request):
    blogs = Blog.objects.order_by('-date')
    return render(request, 'blog_app/all_blogs.html', {'blogs': blogs})

#setting up the page for each blog post to display when a blog_id is requested
def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog_app/detail.html', {'blog': blog})

blog/blog_app/templates/blog_app/Contact.html
{% load static %}
<html lang= "en">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'style.css' %}"/>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js"></script>
    <script src="{% static 'mailform.js'%}"></script>
    <title>Contact Page</title>
</head>

<body>
    <!--Navigation bar-->
    <div class="mailHeading">
    <h1>HAVE SOME QUESTIONS?</h1>
    </div>
    <!--Mail Form-->
    <div class="mail-container">
        <form class="contact-form" action="https://formspree.io/f/mpzbwgdk" method="post">
            <div class="mailform">
                <label>Full Name:<input type="text" name="name" class="name" placeholder="Full name" required /></label>
            </div>
            <div class="mailform">
                <label>Email address:<input type="text" name="mail" class="email" placeholder="youremail@email.com" required /></label>
            </div>
            <div class="mailform">
                <label>Subject:<input type="text" name="subject" class="subject" placeholder="Subject" /></label>
            </div>
            <div class="mailform">
                <label>Message:<textarea name="message" class="message" placeholder="Message" required></textarea></label>
            </div>
                <label><button type="submit" class="mailform-button" name="submit">SEND</button></label>
        </form>
    </div>
    <div class="status">
    </div>

</body>

</html> 

blog/blog_app/templates/blog_app/about.html
<!DOCTYPE html>
<html>
  {% load static%}
<!--
  Author: Asia G
  Links to online sources for icons -->
<script src="https://kit.fontawesome.com/748e0c1f07.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="{% static 'mailform.js'%}"></script>
<link rel="stylesheet" type="text/css" href="{% static  'styles.css' %}">
<head>
  <!-- Author: Amy D
          Output: Adds icone for GitHub, Email and LinkedIn-->
<div class="about-section">
  <button class="mailform-button" id="random">
    <a class="nav-link" style="color:white;"
    href="/"> Return Home</a> </button>


    <h1>Meet the Developers</h1>
    <!--added in quick description-->
    <p>Run the Code is a team of full-stack developers with a passion for designing and bringing ideas<br>
      to life online. We emphasize responsive design, security and scalability for dynamic websites made <br>
      to suit a client's needs. Our team consists of 13 developers from John Jay College. Each person plays<br>
       a different role in bringing each project to life.</p> 
  </div>
</head>

<body>
  <!-- Author: Amy D
          Output: Headers for each card-->
  
  <h2 style="text-align:center">Team Leads</h2>


  <!-- Author: Amy D
          Output: Card layout for each member-->
  <div class="row">
    <div class="column">
      <div class="card">
        <img src="/static/chris-t.png" alt="Christopher" style="width:100%">
        <div class="container">
          <h2><b>Christopher Thorne</b></h2>
          <p class="title">Role: Backend Django Admin</p>
          <p></p>
          
          <!-- Author: Asia G
          Input: Click
          Output: Adds icone for GitHub, Email and LinkedIn-->
          <a href="https://github.com/ChristopherThorne714" class="fab fa-github"></a>
          <a href="https://www.linkedin.com/in/christopher-thorne-645200222/" class="fab fa-linkedin"></a>
          <a href="maito:christhorne714@gmail.com" class="fas fa-envelope"></a>
          <!--FIXME: Add Sang's email code here-->

        </div>
      </div>
    </div>
  
    <div class="column">
      <div class="card">
        <img src="/static/asia.png" alt="Asia" style="width:100%">
        <div class="container">
          <h2><b>Asia Gibson</b></h2>
          <p class="title">Role: Frontend/Lead Source Control </p>
          <p>  </p>

          <!-- Author: Asia G
          Input: Click
          Output: Adds icone for GitHub, Email and LinkedIn-->
          <a href="https://github.com/gibsonasia" class="fab fa-github"></a>
          <a href="https://www.linkedin.com/in/asiagibson/" class="fab fa-linkedin"></a>
          <a href="mailto:gibsonjasia@gmail.com" class="fas fa-envelope"></a>
        </div>
      </div>
    </div>
  
    <div class="column">
      <div class="card">
        <img src="/static/alessandra.png" alt="Alessandra" style="width:100%">
        <div class="container">
          <h2><b>Alessandra Serrano</b></h2>
          <p class="title">Role: Project Manager/Frontend </p>
          <p> Leader focused on project management, website design and front end development</p>
          
          <!-- Author: Asia G
          Input: Click
          Output: Adds icone for GitHub, Email and LinkedIn-->
          <a href="https://github.com/alessandra-s" class="fab fa-github"></a>
          <a href="https://www.linkedin.com/in/alessandra-serrano-1923321a4/" class="fab fa-linkedin"></a>
          <a href="mailto:alessandra.serrano@jjay.cuny.edu" class="fas fa-envelope"></a>
          <!--FIXME: Add Sang's email code here-->
        </div>
      </div>
    </div>
  </div>

  <h2 style="text-align:center">Team Members</h2>

<div class="row">
  
    <div class="column">
        <div class="card">
        <img src="/static/amy.png" alt="Amy" style="width:100%">
        <div class="container">
            <h2><b>Amy Dang</b></h2>
            <p class="title">Role: Front End and GitHub</p>
            <p>Some text that describes me lorem ipsum ipsum lorem.</p>

          <!-- Author: Asia G
          Input: Click
          Output: Adds icone for GitHub, Email and LinkedIn-->
          <a href="#" class="fab fa-github"></a>
          <a href="#" class="fab fa-linkedin"></a>
          <a href="#" class="fas fa-envelope"></a>
          <!--FIXME: Add Sang's email code here-->
        </div>
        </div>
    </div>

    <div class="column">
        <div class="card">
        <img src="/static/ayesha.png" alt="Ayesha" style="width:100%">
        <div class="container">
            <h2><b>Ayesha Akhter</b></h2>
            <p class="title">Role:</p>
            <p>Some text that describes me lorem ipsum ipsum lorem.</p>
          <!-- Author: Asia G
          Input: Click
          Output: Adds icone for GitHub, Email and LinkedIn-->
          <a href="https://github.com/heyayesha" class="fab fa-github"></a>
          <a href="https://linkedin.com/in/ayesha-akhter-b556601a7" class="fab fa-linkedin"></a>
          <a href="mailto: ayakhter64@gmail.com" class="fas fa-envelope"></a>
          <!--FIXME: Add Sang's email code here-->
        </div>
        </div>
    </div>
</div>

<div class="row">
  <div class="column">
    <div class="card">
        <img src="/static/trent.png" alt="Hein" style="width:100%">
        <div class="container">
          <h2><b>Hein Htet Aung</b></h2>
          <p class="title">Role:Backend</p>
          <p></p>

          <!-- Author: Asia G
          Input: Click
          Output: Adds icone for GitHub, Email and LinkedIn-->
          <a href="https://github.com/savvy-trenty" class="fab fa-github"></a>
          <a href="https://www.linkedin.com/in/hein-aung-135100106/" class="fab fa-linkedin"></a>
          <a href="mailto: heinhtetaung257@gmail.com" class="fas fa-envelope"></a>
          <!--FIXME: Add Sang's email code here-->
      </div>
    </div>
  </div>

  <div class="column">
    <div class="card">
        <img src="/static/ibrahima.png" alt="Ibrahima" style="width:100%">
        <div class="container">
          <h2><b>Ibrahima Coulibaly</b></h2>
          <p class="title">Role:</p>
          <p>GitHub / Frontend</p>

          <!-- Author: Asia G
          Input: Click
          Output: Adds icone for GitHub, Email and LinkedIn-->
          <a href="https://github.com/Ibrahima2201" class="fab fa-github"></a>
          <a href="https://www.linkedin.com/in/ibrahima-coulibaly/" class="fab fa-linkedin"></a>
          <a href="mailto:ibsoncouldy95@gmail.com" class="fas fa-envelope"></a>
          <!--FIXME: Add Sang's email code here-->

        </div>
      </div>
    </div>
  
    <div class="column">
      <div class="card">
        <img src="/static/jas.png" alt="Jaspreet" style="width:100%">
        <div class="container">
          <h2><b>Jaspreet Singh</b></h2>
          <p class="title">Role: Frontend</p>
          <p></p>

          <!-- Author: Asia G
          Input: Click
          Output: Adds icone for GitHub, Email and LinkedIn-->
          <a href="https://github.com/Jas424" class="fab fa-github"></a>
          <a href="https://www.linkedin.com/in/jaspreet-singh-3a4203227" class="fab fa-linkedin"></a>
          <a href="mailto: jonathanyanez02@gmail.com" class="fas fa-envelope"></a>
          <!--FIXME: Add Sang's email code here-->
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="column">
    <div class="card">
      <img src="/static/jonathan.png" alt="Jonathan" style="width:100%">
      <div class="container">
        <h2><b>Jonathan Yanez</b></h2>
        <p class="title">Role:Fronted</p>
        <p>Implemented design for blog site</p>

          <!-- Author: Asia G
          Input: Click
          Output: Adds icone for GitHub, Email and LinkedIn-->
          <a href="https://github.com/jonathanyanez02" class="fab fa-github"></a>
          <a href="www.linkedin.com/in/jonathan-yanez-45558114a" class="fab fa-linkedin"></a>
          <a href="#" class="fas fa-envelope"></a>
          <!--FIXME: Add Sang's email code here-->
        </div>
      </div>
    </div>
  
  <div class="column">
    <div class="card">
      <img src="/static/muzzaffar.png" alt="Muzaffar" style="width:100%">
      <div class="container">
          <h2><b>Muzaffar Mukhitdinov</b></h2>
          <p class="title">Role: Blog Writer</p>
          <p></p>

          <!-- Author: Asia G
          Input: Click
          Output: Adds icone for GitHub, Email and LinkedIn-->
          <a href="https://github.com/nolimitmuzaffar" class="fab fa-github"></a>
          <a href="https://www.linkedin.com/in/muzaffarmukhitdinov/" class="fab fa-linkedin"></a>
          <a href="mailto:muzaffarm3030@gmail.com" class="fas fa-envelope"></a>
          <!--FIXME: Add Sang's email code here-->

        </div>
      </div>
    </div>
  
    <div class="column">
      <div class="card">
        <img src="/static/sang.png" alt="SangWon" style="width:100%">
        <div class="container">
          <h2><b>SangWon Park</b></h2>
          <p class="title">Role: Frontend and Backend</p>
          <p></p>

          <!-- Author: Asia G
          Input: Click
          Output: Adds icone for GitHub, Email and LinkedIn-->
          <a href="https://github.com/sangy1" class="fab fa-github"></a>
          <a href="https://www.linkedin.com/in/sangwon-park-885b5b193/" class="fab fa-linkedin"></a>
          <a href="mailto:sangwonpark4@gmail.com" class="fas fa-envelope"></a>
          <!--FIXME: Add Sang's email code here-->

        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="column">
      <div class="card">
        <img src="/static/kirana.png" alt="Kirana" style="width:100%">
        <div class="container">
          <h2><b>Kirana Ali</b></h2>
          <p class="title">Role: Front End and General Writing</p>
          <p> </p>
          
          <!-- Author: Asia G
          Input: Click
          Output: Adds icone for GitHub, Email and LinkedIn-->
          <a href="https://github.com/kirana27" class="fab fa-github"></a>
          <a href="https://www.linkedin.com/in/kirana-ali-0b8370190" class="fab fa-linkedin"></a>
          <a href="mailto:ali.kirana12@gmail.com" class="fas fa-envelope"></a>
          <!--FIXME: Add Sang's email code here-->
        </div>
      </div>
    </div>
  </div>

  <!--ADDED CONTACT TO BOTTOM TO SEE IF IT WORKS WELL-->
<!--Navigation bar-->
<div class="mailHeading">
  <h1>HAVE SOME QUESTIONS?</h1>
  </div>
  <!--Mail Form-->
  <div class="mail-container">
      <form class="contact-form" action="https://formspree.io/f/mpzbwgdk" method="post">
          <div class="mailform">
              <label>Full Name:<input type="text" name="name" class="name" placeholder="Full name" required /></label>
          </div>
          <div class="mailform">
              <label>Email address:<input type="text" name="mail" class="email" placeholder="youremail@email.com" required /></label>
          </div>
          <div class="mailform">
              <label>Subject:<input type="text" name="subject" class="subject" placeholder="Subject" /></label>
          </div>
          <div class="mailform">
              <label>Message:<textarea name="message" class="message" placeholder="Message" required></textarea></label>
          </div>
              <label><button type="submit" class="mailform-button" name="submit">SEND</button></label>
      </form>
  </div>
  <div class="status">
  </div>


</body>


</html>

blog/blog_app/templates/blog_app/all_blogs.html
{% extends 'blog_app/base.html' %}
{% load static %}
{% block content %}

<h1>Blogs</h1>

<h2> I have written {{ blogs.count }} blog{{ blogs.count|pluralize }} </h2>

{% for blog in blogs %}
<!--I don't know why this image is not displaying properly, might have to scrap this part.-->
{% if blog.url %}
<a href="{{ blog.url }}">
  <img src="{{ blog.image.url }}" class="img-fluid mb-2">
</a>
{% else %}

<img src="{{ blog.image.url }}" class="img-fluid mb-2">
{% endif %}
    <a href="{% url 'blog:detail' blog.id %}"><h2>{{ blog.title }}</h2></a>
    <h5>{{ blog.date|date:'M d Y' }}</h5>
    <p>{{ blog.description|striptags|truncatechars:100 }}</p>
    
{% endfor %}

{% endblock %}

blog/blog_app/templates/blog_app/base.html
{% load static%}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>base navigation</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
        <link href="https://fonts.googleapis.com/css?family=Source+Code+Pro:400,900|Source+Sans+Pro:300,900&display=swap" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static "homefull.css" %}"

    </head>

    <body>
        <div class="container">
        <nav class="navbar navbar-expand-sm navbar-dark">  <!-- Navigation Bar with a small amount of items. Dark indicates it being used on a dark background -->
            <a class="navbar-brand" href="#">
                <img src="/static/Run_the_code.png" alt="nav" width="30" height="24" class="d-inline-block align-top">
                <span class="hidden"></span>
              </a>

              <!-- Added button for hamburger menu and elements are added to the button.  -->
            <button
            	class="navbar-toggler"        
            	type="button"                   
            	data-bs-toggle="collapse" 
            	data-bs-target="#toggleMobileMenu" 
            	aria-controls="toggleMenu" 
            	aria-expanded="false" 
            	aria-label="Toggle navigation"
            >
            <span class="navbar-toggler-icon"></span>
            <!-- opens and closes the span tag  -->
            </button>
            <div class="collapse navbar-collapse" id="toggleMobileMenu">
            
                <ul class="navbar-nav ms-auto text-center">
                    <li>
                        <a class="nav-link" href="/">Home</a>  <!-- Used to redirect to homepage  -->
                    </li>
                    <li>
                        <a class="nav-link" href="/about">About us</a>   <!-- Used to redirect to about page  -->
                    </li>
                    <li>
                        <a class="nav-link" href="/all_blogs">Blogs</a>   <!-- Used to redirect to blog  page  -->
                    </li>
                </ul>
            </div>
        </nav>
      </div>
      <div class="container">
    </body>
    <!--Set up the base page from which all_blogs and details will extend-->
    {% block content %} {% endblock content %}
    </html>

blog/blog_app/templates/blog_app/detail.html
<!--might have to change this file path-->
{% extends 'blog_app/base.html' %}

{% block content %}




<br>

<h1>{{ blog.title }}</h1>
<!--I don't know why this image is not displaying properly, might have to scrap this part.-->
{% if project.url %}
<a href="{{ blog.url }}">
  <img src="{{ blog.image.url }}" class="img-fluid mb-2">
</a>
{% else %}

<img src="{{ blog.image.url }}" class="img-fluid mb-2">
{% endif %}
    <a href="{% url 'blog:detail' blog.id %}"><h2>{{ blog.title }}</h2></a>


<h2>--- {{ blog.date|date:'F jS Y' }} ---</h2>

{{ blog.description|safe }}


{% endblock %}

blog/blog_app/templates/blog_app/home.html
{% extends 'blog_app/base.html' %}

{% load static%}
<!-- Some of the code that I used was from my portfolio project that I worked on. I used the following video tutorial  for that project.  -->
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Homepage</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
        <link href="https://fonts.googleapis.com/css?family=Source+Code+Pro:400,900|Source+Sans+Pro:300,900&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="homefull.css">

    </head>
{% block content %} 
    <body>
<!-- Homepage -->
 <section class="intro" id="home">
    <div class="typewriter">
        <h1>The Code Runners.</h1>                                           <!-- h1 = The Code Runners -->
      </div>
    <p class="section__subtitle">John Jay TTP Winter 2022 Cohort</p>         <!-- Makes a subtitle with  "John Jay TTP Winter 2022 Cohort" -->
    <img src="/static/binary-code-greenjpg.jpg" alt="binarycode" class="intro__img">  <!-- Image -->
</section>
</body>
{% endblock content %}
</html>